const express = require('express');
const app = express();
var useragent = require('useragent');
useragent(true);
app.use(express.static(__dirname + "/public"));
const server = app.listen(8000);

const io = require('socket.io')(server);

var indexcounter = 0;
var agentcounter = 0;
var socketConnectionCounter = 0;
var socketThankYouCounter = 0;
var clients = {};
// message count, lastContact dateTime, lastContact messageType, lastcontact messageData, ip, agent, headers
// for now we'll use ip+agent as unique id

function addClient(ip, agent, socketHeaders) {
    console.log("----------\nClients:\nCount:      Agent:\n-------   ----------")
    for (var a in clients) {
        console.log(clients[a], a)
    }
    var myString = agent.toString();
    if (myString in clients) {
        clients[myString] += 1;
    }
    else{
        clients[myString] = 1;
    }
    console.log("Updated: ")
    console.log(clients[myString], myString)
}


// probably not necessary, serves up ejs without even referecing the route or the page ....
//
// app.get('/', function (req, res) {
//     var agent = useragent.parse(req.headers['user-agent'])
//         , another = useragent.fromJSON(JSON.stringify(agent));
//     console.log(agent == another);
//     var ua = useragent.is(req.headers['user-agent']);
//     console.log("user_agent object: ", ua)
//     var agent2 = useragent.parse(req.headers['user-agent'], req.query.jsuseragent);
//     indexcounter++;
//     console.log("**********\nIndex, indexCounter = ", indexCounter);
//     console.log("Detected User Agent: " + agent.toString());
//     console.log("Detected User Agent2: " + agent2.toString());

//     addAgent(agent);

//     res.render("index", { });
// })


io.on('connection', function (socket) { //2

    socketConnectionCounter++;
    console.log("**********\nSocket connection, socketConnectionCounter = ", socketConnectionCounter);

    console.log("Client/socket is connected, Client/socket id  = ", socket.id);

    var thisip = socket.request.connection.remoteAddress;
    var thisagent = socket.request.headers['user-agent'].toString();

    console.log("ip: '" + socket.request.connection.remoteAddress + "'");
    console.log("user-agent:\n  " + socket.request.headers['user-agent']);
    console.log("headers: \n", socket.request.headers);

    addClient(thisip, thisagent, socket.request.headers);

    socket.emit('greeting', { msg: 'Greetings, from server Node, brought to you by Sockets! -Server' }); //3

    socket.on('thankyou', function (data) { //7
        socketThankYouCounter++;
        console.log("**********\nSocket thankyou, socketThankYouCounter = ", socketThankYouCounter);

        console.log(data.msg); //8 (note: this log will be on your server's terminal)
    });

    socket.on("posting_form", function (data) {
        let form_survey = data;
        let number = Math.floor(Math.random() * 1000) + 1;

        var updatedMessage = "You emitted the following: Name=" + data.name + ", Location=" + data.location + ", Language=" + data.language + ", Comment='" + data.comment + "'."
        socket.emit('updated_message', { message: updatedMessage, name: data.name, location: data.location, language: data.language, comments: data.comments });

        var numberMessage = "Your lucky number generated by the server is " + number + ".";
        socket.emit('random_number', { numberMessage: numberMessage, luckyNumber: number } );
    });


});
